name: Java CI with Gradle

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
      
    - name: Run core tests
      run: ./gradlew core:test --no-daemon
    - name: Run server tests
      run: ./gradlew server:test --no-daemon
  deliver:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build client jar
      run: ./gradlew lwjgl3:jar
    - name: Upload client jar
      uses: actions/upload-artifact@v3
      with:
        name: client
        path: lwjgl3/build/lib/*
    - name: Build server jar
      run: ./gradlew server:jar
    - name: Upload server jar
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: server/build/lib/*
    
